# SELECT SECTION
SELECT * FROM PLANES;
SELECT * FROM FLIGHT;
SELECT CURRENT_DATE();


# CREATE SECTION
CREATE DATABASE PROJECT_DBMS;
CREATE TABLE PLANES (
    REG_NUMBER VARCHAR(6) PRIMARY KEY,
    PLANE_NAME CHAR(4) NOT NULL,
    NUMBER_OF_SEAT INT NOT NULL,
    QUANTITY_SEAT_TYPE1 INT,
    QUANTITY_SEAT_TYPE2 INT,
    MANUFACTURER VARCHAR(20)
);

CREATE TABLE FLIGHT (
    FLIGHTID VARCHAR(10) PRIMARY KEY,
    PLANEID VARCHAR(6),
    DEPARTURE_DATE DATE NOT NULL,
    ARRIVAL_DATE DATE NOT NULL ,
    DESTINATION VARCHAR(10) NOT NULL ,
    ORIGIN VARCHAR(10) NOT NULL ,
    QUANTITY_SEAT1 INT,
    QUANTITY_SEAT2 INT,
    FOREIGN KEY (PLANEID) REFERENCES PLANES(REG_NUMBER)
);

# PROCEDURE SECTION
CREATE PROCEDURE FILL_AVAILABLE_SEAT(PLANEID VARCHAR(6))
BEGIN
    DECLARE AVLB_TYPE1 INT DEFAULT 0;
    DECLARE AVLB_TYPE2 INT DEFAULT 0;
    SELECT QUANTITY_SEAT_TYPE1 INTO AVLB_TYPE1 FROM PLANES WHERE REG_NUMBER=PLANEID;
    SELECT QUANTITY_SEAT_TYPE2 INTO AVLB_TYPE2 FROM PLANES WHERE REG_NUMBER=PLANEID;
    UPDATE FLIGHT
        SET QUANTITY_SEAT1=AVLB_TYPE1, QUANTITY_SEAT2=AVLB_TYPE2
        WHERE FLIGHT.PLANEID LIKE PLANEID;
END;

# EXECUTE PROCEDURE SECTION
CALL FILL_AVAILABLE_SEAT("VJ305");

# ALTER SECTION
ALTER TABLE FLIGHT ADD COLUMN NOTE VARCHAR(255);

ALTER TABLE PLANES RENAME COLUMN REG_NUMBER TO PLANEID;
ALTER TABLE PLANES RENAME COLUMN PLANE_NAME TO PLANENAME;
ALTER TABLE PLANES RENAME COLUMN NUMBER_OF_SEAT TO TOTALSEAT;
ALTER TABLE PLANES RENAME COLUMN QUANTITY_SEAT_TYPE1 TO TYPE1SEAT;
ALTER TABLE PLANES RENAME COLUMN QUANTITY_SEAT_TYPE2 TO TYPE2SEAT;


# DROP SECTION
DROP PROCEDURE FILL_AVAILABLE_SEAT;

# TRUNCATE SECTION
TRUNCATE FLIGHT;

