
CREATE DATABASE PROJECT_DBMS;
CREATE TABLE PLANES (
    REG_NUMBER VARCHAR(6) PRIMARY KEY,
    PLANE_NAME CHAR(4) NOT NULL,
    NUMBER_OF_SEAT INT NOT NULL,
    QUANTITY_SEAT_TYPE1 INT,
    QUANTITY_SEAT_TYPE2 INT,
    MANUFACTURER VARCHAR(20)
);

SELECT * FROM PLANES;

